### PR TITLE
Reword and reorganise the funding page

### PR DESCRIPTION
**Pull request by peteryates**
### Context

The funding page needed some CTAs between paragraphs and sections.

### Changes proposed in this pull request

Split the funding page into partials and place CTA's between them where necessary. This is done via the list of partials in the frontmatter.

### Guidance to review

funding-your-training

### CODE REVIEW

**Review by MylesJarvis — COMMENTED** [review]
Title appears to be missing from the Nav bar, I therefore navigated to domain/funding-your-training by hand. It appears there's a missing Hero image too.

**Review by MylesJarvis — COMMENTED** [review]
Open in new tab icon also appears on the new CTA links, which need to be removed.

**Comment by peteryates** [comment]
The new tab icon has been addressed already in DFE-Digital/get-into-teaching-app/pull/676

The reason the funding page is missing from the nav bar is because it's built using front matter from markdown files. Here I switched to HTML because there's a desire for CTA's amongst content and this is the cleanest way. It looks like we'll need to take a different route, and I'm not sure what the best one is. I'll do a bit more investigation tomorrow.

When I looked into this a while ago the other option was to amend our markdown processor (Kramdown) so that we can have 'custom' GiT-specific syntax. However, due to the complexity of our CTAs this might not be ideal.

**Review by MylesJarvis — COMMENTED** [review]
Subject to ensuring that 676 fixes the icons in CTAs for opening in a new tab (these need to go), there's one final change to make:
Screenshot 2020-12-16 at 15 45 57

These two links go to the same page I believe, need the typical text URL to be removed.

**Review by MylesJarvis — APPROVED** [review]
All good now - thanks everyone

**Pull request merged**
