### PR TITLE
Minor SEO fixes

### PR DESCRIPTION
**Pull request by peteryates**
### Trello card

https://trello.com/c/3VUoO7Fg/1467-fix-minor-seo-issues

### Context

* [x] Remove a duplicated story
* [x] Remove duplicate `h1`s on accessibility page
* [x] Rename 'Returning to teaching' story page to 'Returning to the classroom' (opinions please @MylesJarvis, @rosecatt, @EmmaFrith)

Screenshot from 2021-03-25 15-37-00

### CODE REVIEW

**Review by MylesJarvis — DISMISSED** [review]
I'm happy with change in title re returning story, as we use that title elsewhere on the site.

**Comment by EmmaFrith** [comment]
Just a thought re. title - and do say if I'm missing any important context here! 

I'd be keen to try something more personal, aspirational and active, such as 'Be a teacher again'. 

I suspect 'teacher' may also be a more frequently searched term than 'classroom', although this is just a hypothesis. 

Thoughts @rosecatt @MylesJarvis @peteryates ?

**Comment by peteryates** [comment]
I really like "Be a teacher again". Definitely is better-suited on the aspirational front.

Screenshot from 2021-03-26 11-59-44

**Review by MylesJarvis — APPROVED** [review]
LGTM

**Pull request merged**
